HTTP_API_URL = "https://api2.amplitude.com/2/httpapi"
HTTP_API_URL_EU = "https://api.eu.amplitude.com/2/httpapi"
BATCH_API_URL = "https://api2.amplitude.com/batch"
BATCH_API_URL_EU = "https://api.eu.amplitude.com/batch"

IDENTIFY_EVENT = "$identify"
GROUP_IDENTIFY_EVENT = "$groupidentify"
IDENTITY_OP_ADD = "$add"
IDENTITY_OP_APPEND = "$append"
IDENTITY_OP_CLEAR_ALL = "$clearAll"
IDENTITY_OP_PREPEND = "$prepend"
IDENTITY_OP_SET = "$set"
IDENTITY_OP_SET_ONCE = "$setOnce"
IDENTITY_OP_UNSET = "$unset"
IDENTITY_OP_PRE_INSERT = "$preInsert"
IDENTITY_OP_POST_INSERT = "$postInsert"
IDENTITY_OP_REMOVE = "$remove"
UNSET_VALUE = "-"

REVENUE_PRODUCT_ID = "$productId"
REVENUE_QUANTITY = "$quantity"
REVENUE_PRICE = "$price"
REVENUE_TYPE = "$revenueType"
REVENUE_RECEIPT = "$receipt"
REVENUE_RECEIPT_SIG = "$receiptSig"
REVENUE = "$revenue"
AMP_REVENUE_EVENT = "revenue_amount"

MAX_PROPERTY_KEYS = 1024
MAX_STRING_LENGTH = 1024

LOGGER_NAME = "amplitude"
BEFORE_PLUGIN_TYPE = "before"
ENRICHMENT_PLUGIN_TYPE = "enrichment"
DESTINATION_PLUGIN_TYPE = "destination"
