name: Publish to Test PyPI

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: "Preview only (no version bump, no publish)"
        required: true
        default: "true"

jobs:
  authorize:
    name: Authorize
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.actor }} permission check to do a release
        uses: "lannonbr/repo-permission-check-action@2bb8c89ba8bf115c4bfab344d6a6f442b24c9a1f" # 2.0.2
        with:
          permission: "write"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-n-publish:
    name: Build and publish to Test PyPI
    runs-on: ubuntu-latest
    needs: [authorize]
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout for release to Test PyPI
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.9
        uses: actions/setup-python@3542bca2639a428e1796aaa6a2ffef0c0f575566 # v3
        with:
          python-version: 3.9

      - name: Install semantic release
        run: python -m pip install python-semantic-release==10.5.3

      - name: Run Test
        run: python -m unittest discover -s ./src -p 'test_*.py'

      - name: Publish distribution to VCS Release (dry run)
        if: ${{ github.event.inputs.dryRun == 'true' }}
        run: |
          semantic-release -vv version --no-commit --no-tag --no-push --noop

      - name: Publish distribution to VCS Release
        if: ${{ github.event.inputs.dryRun == 'false' }}
        run: |
          git config user.name amplitude-sdk-bot
          git config user.email amplitude-sdk-bot@users.noreply.github.com
          semantic-release version --no-push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish distribution Test PyPI
        if: ${{ github.event.inputs.dryRun == 'false' }}
        uses: pypa/gh-action-pypi-publish@ed0c53931b1dc9bd32cbe73a98c7f6766f8a527e
        with:
          repository_url: https://test.pypi.org/legacy/
